
import { Exercise, Equipment, ExperienceLevel, MuscleGroup, Achievement } from './types';
import { Medal, Flame, Zap, Sunrise, Award, Skull, Crown, BicepsFlexed } from 'lucide-react';

// Banco de Dados Massivo de Exercícios
export const EXERCISE_DATABASE: Exercise[] = [
  // --- PEITO (CHEST) ---
  {
    id: 'c1',
    name: 'Flexão de Braço Clássica',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.SHOULDERS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/IODxDxX7oi4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    description: 'O exercício fundamental da calistenia. Mantenha o corpo em linha reta, desça o peito até quase tocar o chão e empurre com explosão.',
    reps: '10-15',
    sets: 3,
    caloriesPerMinute: 8
  },
  {
    id: 'c2',
    name: 'Supino Reto com Barra',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/rT7DgCr-3pg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    description: 'O rei dos exercícios de peito na academia. Deite-se no banco, desça a barra controladamente até o meio do peito e empurre.',
    reps: '8-12',
    sets: 4,
    caloriesPerMinute: 6
  },
  {
    id: 'c3',
    name: 'Supino Inclinado com Halteres',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.ARMS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/8iPEnn-ltC8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    description: 'Foca na parte superior do peitoral. Ajuste o banco a 30-45 graus. Mantenha os cotovelos levemente fechados.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'c4',
    name: 'Flexão Diamante',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS], // Triceps heavy
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/J0DnG1_S92I/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=J0DnG1_S92I',
    description: 'Junte as mãos formando um diamante. Excelente para parte interna do peito e tríceps.',
    reps: '8-12',
    sets: 3,
    caloriesPerMinute: 9
  },
  {
    id: 'c5',
    name: 'Crossover na Polia Alta',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/taI4XduLpTk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=taI4XduLpTk',
    description: 'Isolamento de peitoral. Mantenha o tronco estável e traga as polias à frente do corpo cruzando levemente.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'c6',
    name: 'Dips (Mergulho em Paralelas)',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM, Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/2z8JmcrW-As/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    description: 'Incline o tronco para frente para focar no peito. Desça até quebrar a paralela dos cotovelos.',
    reps: '8-10',
    sets: 3,
    caloriesPerMinute: 10
  },
  {
    id: 'c7',
    name: 'Peck Deck (Voador)',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/eGjt4lkhuqo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=eGjt4lkhuqo',
    description: 'Máquina isoladora para peitoral. Mantenha os cotovelos na altura dos ombros e comprima no centro.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'c8',
    name: 'Flexão Archer',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/I3q9h-Fk6kM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=I3q9h-Fk6kM',
    description: 'Estenda um braço lateralmente enquanto desce no outro. Prepara para a flexão de um braço.',
    reps: '6-8 por lado',
    sets: 3,
    caloriesPerMinute: 10
  },
  {
    id: 'c9',
    name: 'Supino Declinado',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/LfyQBUKR8SE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=LfyQBUKR8SE',
    description: 'Foca na parte inferior do peitoral. Use um banco declinado.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'c10',
    name: 'Supino Reto com Halteres',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/VmB1G1K7v94/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    description: 'Permite maior amplitude de movimento que a barra. Mantenha os pesos controlados.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'c11',
    name: 'Flexão Declinada',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.ARMS],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/SKPab2YC8BE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=SKPab2YC8BE',
    description: 'Pés elevados em um banco ou cadeira. Foca na porção superior do peito.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 8
  },
  {
    id: 'c12',
    name: 'Pullover com Halter',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.ABS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/5Y8K4tN50Fw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=5Y8K4tN50Fw',
    description: 'Expande a caixa torácica. Deite atravessado no banco e leve o halter atrás da cabeça.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'c13',
    name: 'Flexão Inclinada',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/Me9bHFAxWjk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Me9bHFAxWjk',
    description: 'Mãos apoiadas em um banco ou parede. Foca na parte inferior do peito e é mais fácil para iniciantes.',
    reps: '15-20',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'c14',
    name: 'Svend Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/O2x0lM-tNqQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=O2x0lM-tNqQ',
    description: 'Pressione duas anilhas ou um halter contra o peito e estenda os braços. Foco em contração constante.',
    reps: '15',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'c15',
    name: 'Landmine Press',
    muscleGroup: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.ARMS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/Z9q1u5iB4AA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Z9q1u5iB4AA',
    description: 'Empurre a barra ancorada no chão diagonalmente. Ótimo para parte superior do peito.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 7
  },

  // --- COSTAS (BACK) ---
  {
    id: 'b1',
    name: 'Barra Fixa (Pull Up)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/eGo4IYlbE5g/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    description: 'O melhor construtor de costas. Pegada pronada (palmas para frente). Puxe até o queixo passar a barra.',
    reps: 'Máximo',
    sets: 4,
    caloriesPerMinute: 11
  },
  {
    id: 'b2',
    name: 'Remada Curvada com Barra',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.ARMS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/6FZHJGzMFEc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6FZHJGzMFEc',
    description: 'Mantenha as costas retas, joelhos flexionados. Puxe a barra em direção ao umbigo.',
    reps: '8-10',
    sets: 4,
    caloriesPerMinute: 8
  },
  {
    id: 'b3',
    name: 'Remada Australiana',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/rloXYB8M3vU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=rloXYB8M3vU',
    description: 'Ótimo para iniciantes na calistenia. Entre embaixo de uma barra baixa e puxe o peito até ela.',
    reps: '10-15',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'b4',
    name: 'Puxada Frontal (Pulldown)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/CAwf7n6Luuc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    description: 'Simula a barra fixa. Puxe a barra até a altura superior do peito, contraindo as escápulas.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'b5',
    name: 'Levantamento Terra',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/op9kVnSso6Q/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    description: 'Exercício composto total. Levante a barra do chão mantendo a coluna neutra. Ativa toda a cadeia posterior.',
    reps: '5',
    sets: 3,
    caloriesPerMinute: 12
  },
  {
    id: 'b6',
    name: 'Serrote (Remada Unilateral)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/9efgcAjQe7E/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9efgcAjQe7E',
    description: 'Apoie uma mão e joelho no banco. Puxe o halter trazendo o cotovelo para trás do tronco.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 'b7',
    name: 'Front Lever Tuck',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/d_e8FqgC2T8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=d_e8FqgC2T8',
    description: 'Calistenia avançada. Pendurado na barra, traga os joelhos ao peito e incline o corpo para trás ficando paralelo ao chão.',
    durationSeconds: 15,
    sets: 3,
    caloriesPerMinute: 9
  },
  {
    id: 'b8',
    name: 'Remada Baixa (Triângulo)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/GZbfZ033f74/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    description: 'Sente-se e mantenha a coluna ereta. Puxe o triângulo em direção ao abdômen.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'b9',
    name: 'Muscle Up',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.ARMS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/XgGz3F7jRns/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=XgGz3F7jRns',
    description: 'O movimento supremo da calistenia. Puxe com explosão e transicione o peito para cima da barra.',
    reps: '3-5',
    sets: 3,
    caloriesPerMinute: 15
  },
  {
    id: 'b10',
    name: 'Remada Cavalinho (T-Bar)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.LEGS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/j3Igk5nyZE4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
    description: 'Mantenha a coluna neutra. Puxe a barra em direção ao peito, focando na espessura das costas.',
    reps: '10-12',
    sets: 4,
    caloriesPerMinute: 9
  },
  {
    id: 'b11',
    name: 'Hiperextensão Lombar (Superman)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LEGS], // Glutes
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/z6PJMT2y8GQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=z6PJMT2y8GQ',
    description: 'Deitado de bruços, eleve braços e pernas simultaneamente. Fortalece a lombar.',
    reps: '15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'b12',
    name: 'Puxada Triângulo',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/Hh3eJ7c1WQM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Hh3eJ7c1WQM',
    description: 'Variação da puxada frontal com pegada fechada. Enfatiza a parte inferior do dorsal.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'b13',
    name: 'Pulldown Braços Estendidos',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ABS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/Gk8q139zOgw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Gk8q139zOgw',
    description: 'Mantenha os braços retos e abaixe a barra até a coxa. Isola os dorsais sem usar bíceps.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'b14',
    name: 'Remada Invertida (Supinada)',
    muscleGroup: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/Xg9R2vT8t8k/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Xg9R2vT8t8k',
    description: 'Remada Australiana com palmas para cima. Enfatiza mais o bíceps.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 6
  },

  // --- PERNAS (LEGS) ---
  {
    id: 'l1',
    name: 'Agachamento Livre (Bodyweight)',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/aclHkVaku9U/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=aclHkVaku9U',
    description: 'O básico essencial. Pés na largura dos ombros, desça como se fosse sentar em uma cadeira.',
    reps: '15-20',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 'l2',
    name: 'Agachamento com Barra (Back Squat)',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.ABS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/SW_C1A-rejs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=SW_C1A-rejs',
    description: 'Rei dos exercícios de perna. Barra nas costas, desça até quebrar a paralela. Respire fundo para estabilizar o core.',
    reps: '5-8',
    sets: 4,
    caloriesPerMinute: 10
  },
  {
    id: 'l3',
    name: 'Leg Press 45',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/IZxyjW7MPJQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    description: 'Foco total em quadríceps e glúteos sem carregar a coluna. Não estenda totalmente os joelhos no topo.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'l4',
    name: 'Pistol Squat',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.ABS, MuscleGroup.FLEXIBILITY],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/zqVYUDmmPzI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=zqVYUDmmPzI',
    description: 'Agachamento unilateral de calistenia. Exige muita força, equilíbrio e mobilidade.',
    reps: '5 por perna',
    sets: 3,
    caloriesPerMinute: 12
  },
  {
    id: 'l5',
    name: 'Afundo Búlgaro',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/2C-uNgKwPLE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    description: 'Apoie o pé de trás em um banco ou cadeira. Desça o joelho de trás em direção ao chão.',
    reps: '10 por perna',
    sets: 3,
    caloriesPerMinute: 9
  },
  {
    id: 'l6',
    name: 'Cadeira Extensora',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/YyvSfVjQeL0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    description: 'Isolador de quadríceps. Estenda as pernas completamente e segure 1 segundo no topo.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'l7',
    name: 'Stiff com Barra',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.FULL_GYM, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/CN_7cz3P-1U/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=CN_7cz3P-1U',
    description: 'Foco em posterior de coxa e glúteo. Mantenha as pernas semi-flexionadas e desça o tronco reto.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 'l8',
    name: 'Mesa Flexora',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/1Tq3QdYUuHs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    description: 'Isolador de posterior de coxa. Mantenha o quadril colado no banco ao flexionar.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'l9',
    name: 'Panturrilha em Pé',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/ymm1WdFfXbI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=ymm1WdFfXbI',
    description: 'Apoie-se em um degrau. Desça o calcanhar o máximo possível e suba na ponta dos pés.',
    reps: '15-20',
    sets: 4,
    caloriesPerMinute: 3
  },
  {
    id: 'l10',
    name: 'Elevação Pélvica (Hip Thrust)',
    muscleGroup: MuscleGroup.LEGS, // Focus Glutes
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/xDmFkJxPzeM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=xDmFkJxPzeM',
    description: 'O melhor exercício para glúteos. Apoie as costas no banco e levante o quadril contraindo o glúteo no topo.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'l11',
    name: 'Agachamento Sumô',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [], // Adductors/Glutes
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/Z2F0cC108_E/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Z2F0cC108_E',
    description: 'Pés afastados e pontas para fora. Foca na parte interna da coxa e glúteos.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 'l12',
    name: 'Avanço (Walking Lunge)',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.CARDIO],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/L8fvyb59h-s/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=L8fvyb59h-s',
    description: 'Caminhe dando passadas largas. Mantenha o tronco ereto.',
    reps: '20 passos',
    sets: 3,
    caloriesPerMinute: 9
  },
  {
    id: 'l13',
    name: 'Panturrilha Sentado',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/SC12zL8pEgs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=SC12zL8pEgs',
    description: 'Foca no músculo Sóleo da panturrilha. Coloque um peso sobre os joelhos se estiver em casa.',
    reps: '15-20',
    sets: 4,
    caloriesPerMinute: 2
  },
  {
    id: 'l14',
    name: 'Good Morning',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.BACK], // Hamstrings
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/YA-h3n9L4YU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YA-h3n9L4YU',
    description: 'Similar ao Stiff, mas com a barra (ou mãos) nas costas. Flexione o quadril mantendo as pernas esticadas.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'l15',
    name: 'Agachamento Goblet',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/MeIiIdhvXT4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=MeIiIdhvXT4',
    description: 'Segure um halter ou kettlebell na altura do peito. Ajuda a manter o tronco ereto.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 8
  },
  {
    id: 'l16',
    name: 'RDL com Halteres (Stiff Romeno)',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/JCXUYuzwNrM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    description: 'Mantenha os joelhos levemente dobrados. Desça os halteres rente às pernas sentindo o posterior.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 'l17',
    name: 'Chute Traseiro (Glute Kickback)',
    muscleGroup: MuscleGroup.LEGS, // Glutes
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/vTzcD2Wj24k/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=vTzcD2Wj24k',
    description: 'Em 4 apoios, chute a perna para cima contraindo o glúteo.',
    reps: '15-20 por lado',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'l18',
    name: 'Flexão Nórdica',
    muscleGroup: MuscleGroup.LEGS, // Hamstrings
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/d8PephZ0lIA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=d8PephZ0lIA',
    description: 'Prenda os pés. Desça o tronco controladamente usando apenas o posterior da coxa.',
    reps: '5-8',
    sets: 3,
    caloriesPerMinute: 8
  },
  {
    id: 'l19',
    name: 'Elevação Pélvica Unilateral',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/Bla4W3RzL70/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Bla4W3RzL70',
    description: 'Variação da ponte com uma perna só. Intenso para glúteos.',
    reps: '10-12 por lado',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'l20',
    name: 'Elevação Tibial',
    muscleGroup: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/gK0r8b6zVlM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=gK0r8b6zVlM',
    description: 'Encoste na parede e levante a ponta dos pés. Fortalece a canela e previne dores.',
    reps: '20-25',
    sets: 3,
    caloriesPerMinute: 2
  },

  // --- OMBROS (SHOULDERS) ---
  {
    id: 's1',
    name: 'Desenvolvimento Militar',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/qEwKCR5JCog/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    description: 'Empurre os pesos acima da cabeça. Mantenha o core travado para não arquear as costas.',
    reps: '8-12',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 's2',
    name: 'Pike Push Up',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/sposDXWEB0A/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=sposDXWEB0A',
    description: 'A "flexão de ombro" da calistenia. Corpo em V invertido, topo da cabeça em direção ao chão.',
    reps: '8-10',
    sets: 3,
    caloriesPerMinute: 8
  },
  {
    id: 's3',
    name: 'Elevação Lateral',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/3VcKaXpzqRo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    description: 'Crucial para ombros largos. Levante os pesos até a altura dos ombros, cotovelos levemente dobrados.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 's4',
    name: 'Handstand (Parada de Mão) na Parede',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.ARMS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/M7pQ3fD6XKw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=M7pQ3fD6XKw',
    description: 'Isometria avançada. Apoie os pés na parede e segure o peso do corpo nos braços.',
    durationSeconds: 30,
    sets: 3,
    caloriesPerMinute: 11
  },
  {
    id: 's5',
    name: 'Face Pull (Polia)',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/V8dZqdIe_sI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=V8dZqdIe_sI',
    description: 'Excelente para postura e deltóide posterior. Puxe a corda em direção à testa.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 's6',
    name: 'Elevação Frontal',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/-t7fuZ0KhDA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v/-t7fuZ0KhDA',
    description: 'Foco na parte da frente do ombro. Eleve os braços esticados à frente até a altura dos olhos.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 's7',
    name: 'Desenvolvimento Arnold',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/6Z15_WdXMa4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6Z15_WdXMa4',
    description: 'Gire os punhos enquanto sobe o peso. Trabalha todas as cabeças do ombro.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 7
  },
  {
    id: 's8',
    name: 'Crucifixo Inverso (Peck Deck Inverso)',
    muscleGroup: MuscleGroup.SHOULDERS, // Rear Delt
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.FULL_GYM, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/Q7vj6qB5p4M/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Q7vj6qB5p4M',
    description: 'Sente-se de frente para o aparelho. Abra os braços para trás focando no posterior de ombro.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 's9',
    name: 'Encolhimento de Ombros',
    muscleGroup: MuscleGroup.SHOULDERS, // Traps
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.FULL_GYM, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/g6qqx4jP8Os/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=g6qqx4jP8Os',
    description: 'Segure pesos pesados ao lado do corpo e eleve os ombros em direção às orelhas.',
    reps: '15-20',
    sets: 4,
    caloriesPerMinute: 5
  },
  {
    id: 's10',
    name: 'Remada Alta',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.FULL_GYM, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/22r7LqgZ7mI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=22r7LqgZ7mI',
    description: 'Puxe a barra rente ao corpo até o peito. Foca nos ombros e trapézio.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 's11',
    name: 'Crucifixo Inverso no Cabo',
    muscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/v63z50w9Zdc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=v63z50w9Zdc',
    description: 'Crúze os cabos e abra os braços para trás. Excelente tensão constante no posterior de ombro.',
    reps: '15',
    sets: 3,
    caloriesPerMinute: 5
  },

  // --- BRAÇOS (ARMS) ---
  {
    id: 'a1',
    name: 'Rosca Direta (Barra)',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM, Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/kwG2ipFRgfo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
    description: 'Clássico para bíceps. Mantenha os cotovelos fixos ao lado do corpo.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a2',
    name: 'Tríceps Banco (Mergulho)',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/6kALZikXxLc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6kALZikXxLc',
    description: 'Use um banco ou cadeira. Desça o quadril próximo ao banco flexionando os braços.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'a3',
    name: 'Tríceps Corda (Polia)',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/kiUdbGJmcyY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=kiUdbGJmcyY',
    description: 'Estenda o braço para baixo, abrindo a corda no final do movimento para contração máxima.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a4',
    name: 'Chin Up (Barra Supinada)',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.NONE, Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/_71h6l9eI5U/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=_71h6l9eI5U',
    description: 'Barra fixa com palmas para você. Foca muito no bíceps além das costas.',
    reps: 'Máximo',
    sets: 3,
    caloriesPerMinute: 10
  },
  {
    id: 'a5',
    name: 'Rosca Martelo',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/zC3nLlEcyyw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=zC3nLlEcyyw',
    description: 'Pegada neutra (dedão para cima). Trabalha bíceps e antebraço.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a6',
    name: 'Tríceps Testa',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/nRiJVZDpdL0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=nRiJVZDpdL0',
    description: 'Deitado, desça a barra ou halteres em direção à testa. Mantenha os cotovelos apontados para cima.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'a7',
    name: 'Rosca Concentrada',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/Jvj2wV0vOYU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Jvj2wV0vOYU',
    description: 'Apoie o cotovelo na parte interna da coxa. Isola o pico do bíceps.',
    reps: '12',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a8',
    name: 'Tríceps Francês',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/-j4heW7V1zY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=-j4heW7V1zY',
    description: 'Segure o peso com as duas mãos atrás da cabeça. Estenda os braços para cima.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'a9',
    name: 'Rosca Scott',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/2NnC-1iV0QI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=2NnC-1iV0QI',
    description: 'Use o banco Scott para apoiar os braços. Evita roubo no movimento.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a10',
    name: 'Tríceps Coice (Kickback)',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/6SS6K3lAwZ8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6SS6K3lAwZ8',
    description: 'Incline o tronco. Estenda o braço para trás mantendo o cotovelo alto.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a11',
    name: 'Rosca Inclinada',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/0AUGkch3_Vk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=0AUGkch3_Vk',
    description: 'Sente-se no banco inclinado. Alonga mais o bíceps na parte baixa.',
    reps: '10-12',
    sets: 3,
    caloriesPerMinute: 5
  },
  {
    id: 'a12',
    name: 'Rosca Spider',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/ke2FjX7nFfM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=ke2FjX7nFfM',
    description: 'Peito apoiado no banco inclinado. Braços pendurados. Foco total no pico.',
    reps: '12',
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'a13',
    name: 'Supino Pegada Fechada',
    muscleGroup: MuscleGroup.ARMS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.FULL_GYM],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/nEF0bv2FW94/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=nEF0bv2FW94',
    description: 'Supino com mãos na largura dos ombros. Transfere a carga para o tríceps.',
    reps: '8-10',
    sets: 3,
    caloriesPerMinute: 6
  },

  // --- ABDOMEN (CORE) ---
  {
    id: 'abs1',
    name: 'Prancha Abdominal',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/ASdvN_XEl_c/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    description: 'Isometria essencial. Contraia glúteos e abdômen. Não deixe o quadril cair.',
    durationSeconds: 45,
    sets: 3,
    caloriesPerMinute: 4
  },
  {
    id: 'abs2',
    name: 'Hollow Body Hold',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.LEGS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/44mgUselcDU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=44mgUselcDU',
    description: 'Exercício ginástico. Lombar colada no chão, pernas e braços estendidos flutuando.',
    durationSeconds: 30,
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'abs3',
    name: 'Abdominal Supra (Crunch)',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/Xyd_fa5zoEU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Xyd_fa5zoEU',
    description: 'Curto e controlado. Tire apenas as escápulas do chão soltando o ar.',
    reps: '15-20',
    sets: 3,
    caloriesPerMinute: 3
  },
  {
    id: 'abs4',
    name: 'Elevação de Pernas na Barra',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.ARMS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/7FwGZ8qY5OU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=7FwGZ8qY5OU',
    description: 'Pendurado na barra, eleve as pernas esticadas até tocar a barra (ou até 90 graus).',
    reps: '8-12',
    sets: 3,
    caloriesPerMinute: 8
  },
  {
    id: 'abs5',
    name: 'Abdominal Bicicleta',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/Iwyvozckjak/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Iwyvozckjak',
    description: 'Leve o cotovelo direito ao joelho esquerdo e alterne dinamicamente.',
    durationSeconds: 45,
    sets: 3,
    caloriesPerMinute: 6
  },
  {
    id: 'abs6',
    name: 'Prancha Lateral',
    muscleGroup: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/N_swr99hV74/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=N_swr99hV74',
    description: 'Apoie o antebraço no chão e levante o quadril. Foca nos oblíquos.',
    durationSeconds: 30,
    sets: 3,
    caloriesPerMinute: 5
  },

  // --- CARDIO / HIIT ---
  {
    id: 'hiit1',
    name: 'Burpees',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.LEGS, MuscleGroup.ARMS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/TU8QYVW0gDU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=TU8QYVW0gDU',
    description: 'O exercício mais completo de cardio. Agache, flexão, volte e salte.',
    reps: '10-15',
    sets: 4,
    caloriesPerMinute: 14
  },
  {
    id: 'hiit2',
    name: 'Mountain Climbers',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.ABS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/nmwgirgXLIg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=nmwgirgXLIg',
    description: 'Na posição de prancha, traga os joelhos alternadamente em direção ao peito em alta velocidade.',
    durationSeconds: 45,
    sets: 3,
    caloriesPerMinute: 10
  },
  {
    id: 'hiit3',
    name: 'Polichinelos (Jumping Jacks)',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/c4DAnQ6DtF8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=c4DAnQ6DtF8',
    description: 'Excelente para aquecimento e elevar a frequência cardíaca.',
    durationSeconds: 60,
    sets: 2,
    caloriesPerMinute: 8
  },
  {
    id: 'hiit4',
    name: 'Pular Corda',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.LEGS],
    equipmentRequired: [Equipment.HOME_BASIC],
    difficulty: ExperienceLevel.INTERMEDIATE,
    videoPlaceholder: 'https://img.youtube.com/vi/FJmRQ5iTXKE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=FJmRQ5iTXKE',
    description: 'Cardio de alta intensidade. Mantenha os saltos baixos e rápidos.',
    durationSeconds: 60,
    sets: 3,
    caloriesPerMinute: 12
  },
  {
    id: 'hiit5',
    name: 'Boxe Sombra (Shadow Boxing)',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/K0t02xX_vJA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=K0t02xX_vJA',
    description: 'Simule socos no ar. Mantenha a guarda alta e movimente os pés constantemente.',
    durationSeconds: 60,
    sets: 3,
    caloriesPerMinute: 9
  },
  {
    id: 'hiit6',
    name: 'Corrida no Lugar (High Knees)',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/QPfQdtCkXoA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=QPfQdtCkXoA',
    description: 'Corra sem sair do lugar, elevando os joelhos até a altura do quadril.',
    durationSeconds: 45,
    sets: 3,
    caloriesPerMinute: 10
  },
  {
    id: 'hiit7',
    name: 'Squat Jump (Agachamento com Salto)',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.LEGS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/72BSZdnJYPQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=72BSZdnJYPQ',
    description: 'Agache e exploda em um salto vertical. Aterrisse suavemente.',
    reps: '15',
    sets: 3,
    caloriesPerMinute: 13
  },
  {
    id: 'hiit8',
    name: 'Thruster (Agachamento + Desenvolvimento)',
    muscleGroup: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.SHOULDERS],
    equipmentRequired: [Equipment.HOME_BASIC, Equipment.FULL_GYM],
    difficulty: ExperienceLevel.ADVANCED,
    videoPlaceholder: 'https://img.youtube.com/vi/L219ltL15zk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=L219ltL15zk',
    description: 'Exercício metabólico. Faça um agachamento e use o impulso para empurrar o peso acima da cabeça.',
    reps: '12-15',
    sets: 3,
    caloriesPerMinute: 14
  },

  // --- FLEXIBILIDADE / ALONGAMENTO ---
  {
    id: 'flex1',
    name: 'Posição da Criança',
    muscleGroup: MuscleGroup.FLEXIBILITY,
    secondaryMuscles: [MuscleGroup.BACK],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/2MJGg-dUKh0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=2MJGg-dUKh0',
    description: 'Relaxe as costas e ombros. Ajoelhe-se e estique os braços à frente no chão.',
    durationSeconds: 60,
    sets: 1,
    caloriesPerMinute: 2
  },
  {
    id: 'flex2',
    name: 'Alongamento Cobra',
    muscleGroup: MuscleGroup.FLEXIBILITY,
    secondaryMuscles: [MuscleGroup.ABS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/JDcdhTuycOI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=JDcdhTuycOI',
    description: 'Deite de bruços e empurre o tronco para cima, alongando o abdômen e a coluna.',
    durationSeconds: 30,
    sets: 2,
    caloriesPerMinute: 2
  },
  {
    id: 'flex3',
    name: 'Toque nos Pés (Posterior)',
    muscleGroup: MuscleGroup.FLEXIBILITY,
    secondaryMuscles: [MuscleGroup.LEGS],
    equipmentRequired: [Equipment.NONE],
    difficulty: ExperienceLevel.BEGINNER,
    videoPlaceholder: 'https://img.youtube.com/vi/9r8gYyD8m9w/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9r8gYyD8m9w',
    description: 'Em pé ou sentado, tente alcançar os pés sem dobrar os joelhos.',
    durationSeconds: 45,
    sets: 2,
    caloriesPerMinute: 2
  }
];

export const ACHIEVEMENTS_LIST: Achievement[] = [
    {
        id: 'first_step',
        title: 'Primeiro Passo',
        description: 'Complete seu primeiro treino.',
        icon: Medal
    },
    {
        id: 'on_fire',
        title: 'Em Chamas',
        description: 'Complete 5 treinos no total.',
        icon: Flame
    },
    {
        id: 'warrior',
        title: 'Guerreiro',
        description: 'Complete 10 treinos.',
        icon: Award
    },
    {
        id: 'early_bird',
        title: 'Madrugador',
        description: 'Complete um treino antes das 8 da manhã.',
        icon: Sunrise
    },
    {
        id: 'consistency',
        title: 'Consistência',
        description: 'Treine 3 vezes em uma semana.',
        icon: Zap
    }
];
